name: 'MySQL Action'
description: 'Install MySQL With Custom Configuration'
inputs:
  CONTAINER_NAME:
    description: 'the name of mysql container'
    required: false
    default: 'mysql'
  PORT_MAPPING:
    description: 'the port mapping of mysql container'
    required: false
    default: '3306:3306'
  CHARACTER_SET:
    description: 'the character set of mysql server'
    required: false
    default: 'utf8mb4'
  COLLATION:
    description: 'the character collation of mysql server'
    required: false
    default: 'utf8mb4_general_ci'
  VERSION:
    description: 'the version of mysql server'
    required: false
    default: 'latest'
  ROOT_PASSWORD:
    description: 'super user root password'
    required: false
    default: 'root'
  DATABASE:
    description: 'mysql server init database'
    required: false
    default: 'app'
runs:
  using: 'docker'
  image: 'Dockerfile'