name: Java CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shutdown default mysql
        run: sudo service mysql stop
      - name: Install mysql 5.7
        uses: icomponent/mysql-action@master
        with:
          VERSION: 5.7
          CONTAINER_NAME: mysql
          PORT_MAPPING: 3306:3306
          ROOT_PASSWORD: root
          DATABASE: app
      - name: Install jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Project  test
        run: |
          cd mysql
          java -version
          mvn test