name: Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shutdown default mysql
        run: sudo service mysql stop
      - name: Install mysql 5.7
        uses: icomponent/mysql-action@master
        with:
          VERSION: 5.7
          CONTAINER_NAME: mysql
          PORT_MAPPING: 3309:3306
          ROOT_PASSWORD: root
          INIT_SCRIPTS: |
            CREATE DATABASE auth default charset utf8mb4 COLLATE utf8mb4_general_ci;
            CREATE DATABASE app default charset utf8mb4 COLLATE utf8mb4_general_ci;
            SHOW DATABASES;